name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: ravichandran98
          repo: demo-project
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: workflow1.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
